[package]
name = "samue/utp"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
bridgenet2 = "ffrostflame/bridgenet2@0.5.6"
cmdr = "evaera/cmdr@1.12.0"
simplepath = "untakeranonplay/simplepath@0.1.1"